// Generated by CoffeeScript 1.6.2
(function() {
  var rtc, wireCall;

  rtc = holla.createClient({
    debug: true
  });

  wireCall = function(call) {
    call.ready(function() {
      var stream, _i, _len, _ref, _results;

      _ref = call.streams();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        stream = _ref[_i];
        _results.push(holla.pipe(stream, $(".them")));
      }
      return _results;
    });
    call.on("hangup", function() {
      return $(".them").attr("src", "");
    });
    return $("#hangup").click(function() {
      return call.end();
    });
  };

  $(function() {
    $("#me").hide();
    $("#them").hide();
    $("#whoCall").hide();
    $("#hangup").hide();
    return $("#whoAmI").change(function() {
      var name;

      name = $("#whoAmI").val();
      $(".me").show();
      $(".them").show();
      $("#whoAmI").remove();
      $("#whoCall").show();
      $("#hangup").show();
      return holla.createFullStream(function(err, stream) {
        if (err) {
          throw err;
        }
        holla.pipe(stream, $(".me"));
        return rtc.register(name, function(err) {
          if (err) {
            throw err;
          }
          console.log("Registered as " + name + "!");
          rtc.on("call", function(call) {
            console.log("Inbound call", call);
            call.setLocalStream(stream);
            call.answer();
            return wireCall(call);
          });
          return $("#whoCall").change(function() {
            var toCall;

            toCall = $("#whoCall").val();
            return rtc.createCall(function(err, call) {
              if (err) {
                throw err;
              }
              console.log("Created call", call);
              call.setLocalStream(stream);
              return call.add(toCall, function(err) {
                if (err != null) {
                  throw err;
                }
                return wireCall(call);
              });
            });
          });
        });
      });
    });
  });

}).call(this);
